# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - studentperdoc

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://studentpredoc.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_f2fc2a2c6e5749aca9dd8d10312c87a2 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_2e4328e76e00486e93ea60f4fba9f2e6 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: studentpredoc.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_f2fc2a2c6e5749aca9dd8d10312c87a2 }}/mltest:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'studentperdoc'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_8bef61ecea84420f93d1d8f4021e51c2 }}
        images: 'studentpredoc.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_f2fc2a2c6e5749aca9dd8d10312c87a2 }}/mltest:${{ github.sha }}'